-- Agregar "FALLA NO ESTANDARIZADA" a todos los muros que ya tienen OTROS
-- 119 combinaciones elemento/ambiente
INSERT INTO og_catalogo (elemento, revision, item_revision, tolerancia, ambiente, fase, activo)
VALUES
  ('B MACHON Dormitorio 1 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('B MACHON Dormitorio 1 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('B MACHON Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('B MACHON Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('B TABIQUE Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('B TABIQUE Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('B TABIQUE Pasillo TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO Baño Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO Baño Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO Baño Pasillo TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO CENTRAL TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO Cocina TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('MURO Cocina TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('MURO Cocina TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('MURO Dormitorio 1 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO Dormitorio 1 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO Dormitorio 1 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO Dormitorio 1 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO Dormitorio 1 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO Dormitorio 1 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO Dormitorio 2_Dormitorio 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('MURO Dormitorio 3 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO Dormitorio 3 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('MURO Dormitorio 3 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO Dormitorio 3 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('MURO Dormitorio 3 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO EXTERIOR TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO EXTERIOR TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO EXTERIOR TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO EXTERIOR TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO EXTERIOR TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO EXTERIOR TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO LOGIA TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('MURO LOGIA TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('MURO Living Comedor TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO Living Comedor TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('MURO Living Comedor TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('MURO Living Comedor TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO Living Comedor TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('MURO Living Comedor TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('MURO Living Comedor TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('MURO Living Comedor TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('MURO Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('MURO Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('MURO TABLERO TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Acceso', 'OBRA GRUESA', true),
  ('MURO TABLERO TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Acceso', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('MURO VENTANA TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('MURO VENTANAL TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO VENTANAL TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('MURO VENTANAL TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('Muro Dormitorio 3 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('Muro Dormitorio 3 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('Muro Pasillo TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('TABIQUE Acceso TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Acceso', 'OBRA GRUESA', true),
  ('TABIQUE Acceso TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('TABIQUE Acceso TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Acceso', 'OBRA GRUESA', true),
  ('TABIQUE Acceso TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('TABIQUE BAÑO BDormitorio 1 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE BAÑO BDormitorio 1 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE BDormitorio 1 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE BDormitorio 1 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE BDormitorio 1 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE BDormitorio 1 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE BDormitorio 1 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Baño Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Baño Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Baño Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Baño Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Baño Pasillo TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Baño Pasillo TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Cocina TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('TABIQUE Cocina TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('TABIQUE Cocina TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Living Comedor', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 1 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 1 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 1 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 1 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 1 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 1 TRAMO 4', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 2 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 2 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 2 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 3', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 3 TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 3 TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('TABIQUE Dormitorio 3 TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 2', 'OBRA GRUESA', true),
  ('TABIQUE Living Comedor TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('TABIQUE Living Comedor TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('TABIQUE Living Comedor TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Cocina', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 1', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 2', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Dormitorio 1', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Baño Pasillo', 'OBRA GRUESA', true),
  ('TABIQUE Pasillo TRAMO 3', 'MURO', 'OTROS', 'FALLA NO ESTANDARIZADA', 'Dormitorio 1', 'OBRA GRUESA', true);
